services:
  # Backend API Gateway
  api-gateway:
    container_name: api-gateway
    image: nest-api-gateway:latest
    restart: always
    depends_on:
      - nats
    ports:
      - '3000:3000'
    networks:
      - nest_network
    env_file:
      - .env # Load variables from .env file on the server

  # Todo Microservice
  todo-service:
    container_name: todo-service
    image: nest-todo-service:latest
    restart: always
    depends_on:
      - postgres_db
      - nats
    networks:
      - nest_network
    env_file:
      - .env # Load variables from .env file on the server

  # Database
  postgres_db: # This should match what you use in your pull command
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  # NATS Message Broker
  nats: # This should match what you use in your pull command
    container_name: nats
    image: nats:latest # NOT 'nats:latest-alpine'
    restart: always
    ports:
      - '4222:4222'
    networks:
      - nest_network

networks:
  nest_network:
    driver: bridge

volumes:
  postgres_data:
